// Generated by gencpp from file lab7/test.msg
// DO NOT EDIT!


#ifndef LAB7_MESSAGE_TEST_H
#define LAB7_MESSAGE_TEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab7
{
template <class ContainerAllocator>
struct test_
{
  typedef test_<ContainerAllocator> Type;

  test_()
    : A(0)
    , B(0)
    , Sum(0)  {
    }
  test_(const ContainerAllocator& _alloc)
    : A(0)
    , B(0)
    , Sum(0)  {
  (void)_alloc;
    }



   typedef int64_t _A_type;
  _A_type A;

   typedef int64_t _B_type;
  _B_type B;

   typedef int64_t _Sum_type;
  _Sum_type Sum;





  typedef boost::shared_ptr< ::lab7::test_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab7::test_<ContainerAllocator> const> ConstPtr;

}; // struct test_

typedef ::lab7::test_<std::allocator<void> > test;

typedef boost::shared_ptr< ::lab7::test > testPtr;
typedef boost::shared_ptr< ::lab7::test const> testConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab7::test_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab7::test_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab7::test_<ContainerAllocator1> & lhs, const ::lab7::test_<ContainerAllocator2> & rhs)
{
  return lhs.A == rhs.A &&
    lhs.B == rhs.B &&
    lhs.Sum == rhs.Sum;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab7::test_<ContainerAllocator1> & lhs, const ::lab7::test_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab7

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab7::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab7::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab7::test_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab7::test_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab7::test_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab7::test_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab7::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1459700de7bba184f907aed36761b8d";
  }

  static const char* value(const ::lab7::test_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1459700de7bba18ULL;
  static const uint64_t static_value2 = 0x4f907aed36761b8dULL;
};

template<class ContainerAllocator>
struct DataType< ::lab7::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab7/test";
  }

  static const char* value(const ::lab7::test_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab7::test_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 A\n"
"int64 B\n"
"\n"
"int64 Sum\n"
;
  }

  static const char* value(const ::lab7::test_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab7::test_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.A);
      stream.next(m.B);
      stream.next(m.Sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct test_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab7::test_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab7::test_<ContainerAllocator>& v)
  {
    s << indent << "A: ";
    Printer<int64_t>::stream(s, indent + "  ", v.A);
    s << indent << "B: ";
    Printer<int64_t>::stream(s, indent + "  ", v.B);
    s << indent << "Sum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.Sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB7_MESSAGE_TEST_H
